export type CustomerTypes = {
  clientid: number;
  name: string;
  address: string;
  contactno: string;
  contactperson1: string;
  contactno1: string;
  contactperson2: string;
  contactno2: string;
  email: string;
  city: string;
  district: string;
  state: string;
  gstno: string;
  balanceamt: string;
  licenseno: string;
  licenseissuedt: string;
  licenseexpirydt: string;
  licenseauthority: string;
  wholesale_licenseno: string;
  wholesale_licenseissuedt: string;
  wholesale_licenseexpirydt: string;
  wholesale_licenseauthority: string;
  type: number;
  status: number;
};
